area/common:
- libraries/src/AWS.Lambda.Powertools.Common/*
- libraries/src/AWS.Lambda.Powertools.Common/**/*

area/logging:
- libraries/src/AWS.Lambda.Powertools.Logging/*
- libraries/src/AWS.Lambda.Powertools.Logging/**/*

area/metrics:
- libraries/src/AWS.Lambda.Powertools.Metrics/*
- libraries/src/AWS.Lambda.Powertools.Metrics/**/*

area/tracing:
- libraries/src/AWS.Lambda.Powertools.Tracing/*
- libraries/src/AWS.Lambda.Powertools.Tracing/**/*