name: Build .NET

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

defaults:
  run:
    working-directory: ./libraries

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 6.0 &  8.0
        uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # 4.0.0
        with:
          dotnet-version: |
            6.0.405
            8.0.101
      - name: Build
        run: dotnet build --configuration Release
      - name: Test Examples
        run: dotnet test ../examples/
      - name: Test & Code Coverage
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./codecov --verbosity normal
      - name: Codecov
        uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # 4.3.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: unittests
          fail_ci_if_error: false
          name: codecov-lambda-powertools-dotnet
          verbose: true
          directory: ./libraries/codecov
