name: Build .NET

on:
  push:
    paths:
      - "libraries/**"
    branches: [develop, main]
  pull_request:
    paths:
      - "libraries/**"
    branches: [develop, main]

defaults:
  run:
    working-directory: ./libraries

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Setup .NET 6.0 &  8.0
        uses: actions/setup-dotnet@87b7050bc53ea08284295505d98d2aa94301e852 # 4.2.0
        with:
          dotnet-version: |
            6.0.405
            8.0.101
      - name: Build
        run: dotnet build --configuration Release
      - name: Test Examples
        run: dotnet test ../examples/
      - name: Test & Code Coverage
        run: dotnet test --filter "Category!=E2E" --collect:"XPlat Code Coverage" --results-directory ./codecov --verbosity normal
      - name: Codecov
        uses: codecov/codecov-action@0da7aa657d958d32c117fc47e1f977e7524753c7 # 5.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: false
          name: codecov-lambda-powertools-dotnet
          verbose: true
          directory: ./libraries/codecov
