name: Docs

on:
  push:
    branches:
      - develop

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.8"
      - name: Capture branch and tag
        id: branch_name
        run: |
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build docs website
        run: make build-docs-website
      - name: Deploy all docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - name: Configure api docs generator
        run: |
          curl -LJO https://github.com/dotnet/docfx/releases/download/v2.56.7/docfx.zip 
          unzip docfx.zip -d /docfx && rm docfx.zip
          export PATH="/docfx:$PATH"
      - name: Build api docs 
        run: |
          cd apidocs
          docfx docfx.json
      - name: Release API docs to latest
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apidocs/_site
          keep_files: true
          destination_dir: latest/api