# PROCESS
#
# 1. Deploy the core and AOT stacks using the infra deployment workflow.
# 2. Run the E2E tests after the infrastructure is deployed.
# 3. Destroy the CDK stacks after the tests are completed.

# USAGE
#
# This workflow is triggered on push to the develop branch or manually via workflow_dispatch.

name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:

  deploy-core-stack:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/e2e-infra-deploy.yml


  run-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
  #    needs: [deploy-core-stack, deploy-aot-stack]
    needs: [deploy-core-stack]
    steps:
     - name: Checkout code
       uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    
     - name: Set up .NET
       uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3
       with:
         dotnet-version: '8.x'
         
     - name: Install AWS Lambda .NET CLI Tools
       run: dotnet tool install -g Amazon.Lambda.Tools
    
     - name: Run Core Tests
       run: |
         cd libraries/tests/e2e/functions/core
         dotnet test
    
     - name: Destroy Core Stack
       if: always()
       uses: ./.github/workflows/e2e-infra-destroy.yml
      
#  destroy-core-stack:
#    needs: run-tests
#    uses: ./.github/workflows/e2e-infra-destroy.yml
