name: Record PR details

on:
  pull_request:
    types: [opened, edited, closed]

jobs:
  record_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: "Extract PR details"
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const script = require('.github/scripts/save_pr_details.js')
            await script({github, context, core})
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: pr
          path: pr.txt
